import { Product, Category } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    slug: "climatisation-ac",
    name: "Climatiseurs & Confort",
    description: "Systèmes de climatisation haute efficacité et rafraîchisseurs d'air haut de gamme.",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800&auto=format&fit=crop",
    itemCount: 42,
  },
  {
    id: "cat-2",
    slug: "mode-luxe",
    name: "Mode & Tendances",
    description: "Collection exclusive de vêtements, streetwear chic et accessoires tendance.",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=800&auto=format&fit=crop",
    itemCount: 128,
  },
  {
    id: "cat-3",
    slug: "high-tech",
    name: "High-Tech & Smart",
    description: "Montres connectées, écouteurs sans fil et gadgets de dernière génération.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    itemCount: 64,
  },
  {
    id: "cat-4",
    slug: "accessoires-chaussures",
    name: "Chaussures & Maroquinerie",
    description: "Sneakers premium, sacs en cuir et accessoires de mode raffinés.",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop",
    itemCount: 95,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    slug: "climatiseur-inverter-split-12000-btu",
    name: "Climatiseur Inverter Split 12 000 BTU - EcoCool Silent",
    shortDescription: "Ultra silencieux, économie d'énergie jusqu'à 60%, filtration d'air plasma HD.",
    description: "Profitez d'un confort thermique absolu avec le Climatiseur Inverter EcoCool 12 000 BTU. Équipé du filtre antibactérien HD plasma, d'un moteur Inverter intelligent et d'une connectivité Wi-Fi pour contrôle à distance depuis votre smartphone. Idéal pour pièces de 20 à 35 m².",
    price: 245000,
    originalPrice: 290000,
    discountPercentage: 15,
    rating: 4.9,
    reviewCount: 38,
    category: "climatisation-ac",
    tags: ["Climatiseur", "Inverter", "Top Vente", "EcoCool"],
    featuredImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1000&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614633833026-062060032e2c?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1000&auto=format&fit=crop",
    ],
    attributes: [
      { id: "attr-puissance", name: "Puissance", options: ["9000 BTU", "12000 BTU", "18000 BTU", "24000 BTU"] },
      { id: "attr-couleur", name: "Finition", options: ["Blanc Mat", "Noir Miroir"] },
    ],
    variants: [
      { id: "var-1-1", sku: "AC-12K-W", name: "12000 BTU - Blanc Mat", price: 245000, originalPrice: 290000, attributes: { Puissance: "12000 BTU", Finition: "Blanc Mat" }, stock: 15 },
      { id: "var-1-2", sku: "AC-12K-B", name: "12000 BTU - Noir Miroir", price: 265000, originalPrice: 310000, attributes: { Puissance: "12000 BTU", Finition: "Noir Miroir" }, stock: 8 },
      { id: "var-1-3", sku: "AC-18K-W", name: "18000 BTU - Blanc Mat", price: 340000, originalPrice: 390000, attributes: { Puissance: "18000 BTU", Finition: "Blanc Mat" }, stock: 10 },
    ],
    isNew: true,
    isBestSeller: true,
    stock: 33,
    inStock: true,
  },
  {
    id: "prod-2",
    slug: "ensemble-streetwear-oversized-luxe",
    name: "Ensemble Streetwear Oversized 'Urban Velvet'",
    shortDescription: "Coton lourd 450g/m², coupe moderne tombé parfait, finitions haute couture.",
    description: "Cet ensemble Streetwear Urban Velvet combine élégance urbaine et confort absolu. Conçu en coton biologique 450 GSM avec broderies haute définition, il offre une allure contemporaine et un confort thermique exceptionnel.",
    price: 38000,
    originalPrice: 48000,
    discountPercentage: 20,
    rating: 4.8,
    reviewCount: 54,
    category: "mode-luxe",
    tags: ["Fashion", "Oversized", "Streetwear", "Exclusif"],
    featuredImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop",
    ],
    attributes: [
      { id: "attr-size", name: "Taille", options: ["S", "M", "L", "XL"] },
      { id: "attr-color", name: "Couleur", options: ["Noir Profond", "Beige Écrus", "Vert Olive"] },
    ],
    variants: [
      { id: "var-2-1", sku: "ST-BLK-M", name: "Noir Profond - M", price: 38000, originalPrice: 48000, attributes: { Couleur: "Noir Profond", Taille: "M" }, stock: 12 },
      { id: "var-2-2", sku: "ST-BLK-L", name: "Noir Profond - L", price: 38000, originalPrice: 48000, attributes: { Couleur: "Noir Profond", Taille: "L" }, stock: 20 },
      { id: "var-2-3", sku: "ST-BEI-M", name: "Beige Écrus - M", price: 38000, originalPrice: 48000, attributes: { Couleur: "Beige Écrus", Taille: "M" }, stock: 7 },
    ],
    isNew: true,
    isBestSeller: true,
    stock: 39,
    inStock: true,
  },
  {
    id: "prod-3",
    slug: "ecouteurs-sans-fil-pro-noise-cancelling",
    name: "Écouteurs Sans-Fil Pro X-Sound Studio ANC",
    shortDescription: "Réduction de bruit active intelligente, autonomie 36h, audio spatial 3D.",
    description: "Plongez au cœur du son avec les écouteurs X-Sound Studio ANC. Leur technologie de réduction de bruit active adaptative de 45 dB neutralise les bruits extérieurs pour une clarté vocale et musicale inégalée.",
    price: 45000,
    originalPrice: 65000,
    discountPercentage: 30,
    rating: 4.7,
    reviewCount: 92,
    category: "high-tech",
    tags: ["High-Tech", "Audio", "ANC", "Bluetooth 5.4"],
    featuredImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop",
    ],
    attributes: [
      { id: "attr-color-anc", name: "Finition", options: ["Noir Carbone", "Blanc Argent", "Titanium"] },
    ],
    variants: [
      { id: "var-3-1", sku: "ANC-BLK", name: "Noir Carbone", price: 45000, originalPrice: 65000, attributes: { Finition: "Noir Carbone" }, stock: 25 },
      { id: "var-3-2", sku: "ANC-WHT", name: "Blanc Argent", price: 45000, originalPrice: 65000, attributes: { Finition: "Blanc Argent" }, stock: 14 },
    ],
    isNew: false,
    isBestSeller: true,
    stock: 39,
    inStock: true,
  },
  {
    id: "prod-4",
    slug: "sneakers-leather-minimalist-edition",
    name: "Sneakers Cuir Minimalistes 'Vanguard-01'",
    shortDescription: "Cuir Nappa véritable, semelle ergonomique en caoutchouc naturel vulcanisé.",
    description: "La Vanguard-01 réinvente la basket classique avec un souci extrême du détail. Fabriquée à la main en cuir de veau Nappa pleine fleur, elle allie durabilité, flexibilité et style polyvalent.",
    price: 55000,
    originalPrice: 70000,
    discountPercentage: 21,
    rating: 4.9,
    reviewCount: 41,
    category: "accessoires-chaussures",
    tags: ["Sneakers", "Cuir", "Premium", "Chaussures"],
    featuredImage: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=1000&auto=format&fit=crop",
    ],
    attributes: [
      { id: "attr-pointure", name: "Pointure", options: ["40", "41", "42", "43", "44", "45"] },
    ],
    variants: [
      { id: "var-4-42", sku: "SNK-42", name: "Pointure 42", price: 55000, originalPrice: 70000, attributes: { Pointure: "42" }, stock: 11 },
      { id: "var-4-43", sku: "SNK-43", name: "Pointure 43", price: 55000, originalPrice: 70000, attributes: { Pointure: "43" }, stock: 9 },
    ],
    isNew: true,
    isBestSeller: false,
    stock: 20,
    inStock: true,
  },
];
